server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
    client:
      register-with-eureka: false
      fetch-register: false    #server should not fetch registry from itself
      service-url:
        defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 0    #does not wait on startup

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN